---
all:
  children:
    linux:
      hosts:
        bastion:
          ansible_host: "{{ vault_host_bastion }}"
          common_hostname: "bastion.aws.noriki.me"
        zabbix_server:
          ansible_host: "{{ vault_host_zabbix_server }}"
          ansible_user: root
          common_hostname: "monitor.noriki.me"
      vars:
        ansible_python_interpreter: /usr/bin/python3

