---
- name: Install epel-release
  dnf:
    name: epel-release
    state: present

- name: Install wireguard-tools
  dnf:
    name: wireguard-tools
    state: present

- name: Ensure /etc/wireguard directory exists
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Enable and start systemd-resolved service
  systemd:
    name: systemd-resolved
    state: started
    enabled: yes

- name: Configure NetworkManager to use systemd-resolved backend
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    create: yes
    section: main
    option: dns
    value: systemd-resolved
    mode: '0644'
  notify: Restart NetworkManager

- name: Flush handlers to apply NetworkManager changes
  meta: flush_handlers

- name: Create symlink for /etc/resolve.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

